openapi: 3.0.0
info:
    title: 'Truescape mobile-app mocked API documentation'
    contact:
        email: info@devolon.fi
    license:
        name: 'Apache 2.0'
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local Server
